### ISSUE TITLE
Plugin nulls out intent data on Android so it can't be used by other code

### ISSUE THREAD

**Issue by Justin-Credible** [EddyVerbruggen/Custom-URL-scheme#155]
This plugin has two places in `LaunchMyApp.java` with explicit calls to `intent.setData(null)` if an arbitrary key (`platform.telerik.com`) is not present (see lines [31](https://github.com/EddyVerbruggen/Custom-URL-scheme/blob/master/src/android/nl/xservices/plugins/LaunchMyApp.java#L31) and [63](https://github.com/EddyVerbruggen/Custom-URL-scheme/blob/master/src/android/nl/xservices/plugins/LaunchMyApp.java#L63)). The result is that any other code (such as another plugin) that uses the intent to get data will always get null.

There is a comment above these lines:

`// Telerik LiveSync needs the data object as well, see /pull/3 in the Telerik Verified Plugins fork`

but it doesn't explain why this plugin is modifying the intent data. If the `setData(null)` calls can't be removed from the plugin, the comment should be updated to state why it is necessary. Also the documentation should warn the user that if this plugin is used on Android, other plugins may never receive the intent data.

**Comment by EddyVerbruggen** [comment]
Any specific other plugin you're having trouble with because of this?

**Comment by Justin-Credible** [comment]
I just finished writing [this plugin](https://github.com/Justin-Credible/cordova-plugin-yozio) which caused me to run into this issue. This isn't really an issue with my specific plugin, but rather the Yozio SDK itself is looking in the intent for data which is nulled out by this plugin.

My solution was to remove this plugin so the intent data doesn't get nulled out.

**Comment by EddyVerbruggen** [comment]
You're right, it's not correct.

At the time this plugin was created the debate of SPA vs MPA (single- vs multipage app) was up in the air and it made sense to be careful not to break MPA compatibility; if you have multiple html pages all evaluating the handleOpenURL function on pageload then it would be triggered multiple team leading to potential weird behaviour in your app. That's why I decided to clear the intent after first usage but took a defensive approach. Not defensive enough considering a few other plugins stopped working.

From today (v 4.1.5, just published to npm) this plugin no longer clears the intent unless you set this preference in `config.xml`:

```xml
<preference name="CustomURLSchemePluginClearsAndroidIntent" value="true" />
```

**Comment by Justin-Credible** [comment]
Excellent. Thanks!
