### ISSUE TITLE
Windows 10 refreshes on open

### ISSUE THREAD

**Issue by trumpet2012** [EddyVerbruggen/Custom-URL-scheme#179]
Hi,

I'm using the plugin for Windows Phone 10 and every time the app opens the home page is getting reloaded which is causing the `handleOpenURL` method to not be called. 

This is occurring regardless of whether the app is closed or already open when opening the link.

I was able to solve this problem for me by removing the `StartPage` attribute from the plugin.xml shown below:

```xml
<uap:Extension Category="windows.protocol" StartPage="www/index.html">
        <uap:Protocol Name="$URL_SCHEME" />
</uap:Extension>
```

Is this an issue that anyone else is having? If so, do you think removing this attribute is a valid fix? It is working fine without it for me, so it doesn't seem to be required.

Thanks!

**Comment by davidgv88** [comment]
Thank you!! I have the same issue. This error only appears in W10 (Universal Windows APP). Is secure remove all StartPage?

Or only you should eliminate the StartPage Attribute from package.windows10.appxmanifest file?

**Comment by edgahan** [comment]
I'm trying to get a Windows 10 app working, seem to be having the same issue you were originally having (the app loads up on the custom url, but the homepage refreshes so the url handler function isn't called). 


I'm still having this issue even using the latest commit.  It's worth noting:
1) that in debug mode in Visual Studio everything works fine - when distributed via hockey app it stops working.
2) Without this fix the app just crashes - it goes back to Microsoft Edge entirely.
3) I've tried using both these methods in `LaunchMyApp.js`, but activatedHandler is never called

```
WinJS.Application.addEventListener("activated", activatedHandler, false);
Windows.UI.WebUI.WebUIApplication.addEventListener("activated", activatedHandler, false);
```

4) I've read about having to call `WinJS.Application.start();` - which I don't personally think is the right thing to do, but alas I've tried it as well, no success.

Any ideas? Are you running this in production?

**Comment by edgahan** [comment]
I think I solved this issue. For anybody else the problem has been fixed in cordova-cli and cordova-windows.

There were some issues with the windows app restarting instead of resuming that were resolved here: https://issues.apache.org/jira/browse/CB-10446

I was using cordova@5.3.3 which meant when I ran `cordova platform add windows` it wasn't pulling in the fixes (which had to do with StartPage values). Updating cordova and optionally running something like `cordova platform add https://github.com/apache/cordova-windows` fixed the issue for me.
