### ISSUE TITLE
IOS Phonegap 3.7.0 handleOpenURL is not being called on app open.

### ISSUE THREAD

**Issue by benmcmaster** [EddyVerbruggen/Custom-URL-scheme#72]
In Phonegap 3.7.0 on IOS builds handleOpenURL is not being called when the app opens. However, when the app is in the background it is getting called as normal.

Reverted back to Phonegap 3.6.3 and everything works fine.

**Comment by EddyVerbruggen** [comment]
Yeah, see the big fat warning [here](https://github.com/EddyVerbruggen/Custom-URL-scheme#beware-this-apache-cordova-issue-causes-problems-with-cordova-ios-370-the-handleopenurl-function-is-not-invoked-upon-cold-start-use-a-higher-or-lower-version-than-370) as well as several other issue reports in this repo.

It's caused by a Cordova-iOS bug.
